In [1]:
import particles_mod.Icosphere as ico
import numpy as np
import matplotlib.pyplot as plt
import libMobility as lm





   ██╗   ██╗██╗     ███╗   ███╗██████╗
   ██║   ██║██║     ████╗ ████║██╔══██╗
   ██║   ██║██║     ██╔████╔██║██████╔╝
   ╚██╗ ██╔╝██║     ██║╚██╔╝██║██╔═══╝
    ╚████╔╝ ███████╗██║ ╚═╝ ██║██║
     ╚═══╝  ╚══════╝╚═╝     ╚═╝╚═╝
    VIRTUAL   LAB    MODELING  PLATFORM




06/06/2025 16:07:40 - VLMP - INFO - Starting VLMP... 
06/06/2025 16:07:40 - VLMP - ERROR - No module named 'orthopoly' (__init__.py:187)
06/06/2025 16:07:40 - VLMP - ERROR - [Model] Error importing model type component CORONAVIRUS (__init__.py:188)
06/06/2025 16:07:40 - VLMP - ERROR - No module named 'Bio' (__init__.py:187)
06/06/2025 16:07:40 - VLMP - ERROR - [Model] Error importing model type component ENM (__init__.py:188)
06/06/2025 16:07:40 - VLMP - ERROR - No module named 'pyquaternion' (__init__.py:187)
06/06/2025 16:07:40 - VLMP - ERROR - [Model] Error importing model type component HELIX (__init__.py:188)
06/06/2025 16:07:40 - VLMP - ERROR - No module named 'Bio' (__init__.py:187)
06/06/2025 16:07:40 - VLMP - ERROR - [Model] Error importing model type component IDP (__init__.py:188)
06/06/2025 16:07:40 - VLMP - ERROR - No module named 'Bio' (__init__.py:187)
06/06/2025 16:07:40 - VLMP - ERROR - [Model] Error importing model type component KB (__init__.py:188)
06/06/2025 16:07:

In [2]:
radius = 5.0
density = 1.0

icosphere = ico.IcoSphere(radius, density)


06/06/2025 16:07:40 - VLMP - INFO - [VLMP] Starting VLMP 
06/06/2025 16:07:40 - VLMP - DEBUG - [VLMP] Processing "system" component ({'type': 'simulationName', 'parameters': {'simulationName': 'Icosphere'}}), type "simulationName" (VLMP.py:194)
06/06/2025 16:07:40 - VLMP - WARNING - [VLMP] (system) Component name not specified, using "simulationName". 
06/06/2025 16:07:40 - VLMP - DEBUG - [VLMP] (system) Component name "simulationName". (VLMP.py:200)
06/06/2025 16:07:40 - VLMP - DEBUG - [VLMP] (system) Component parameters "{'simulationName': 'Icosphere'}" (VLMP.py:207)
06/06/2025 16:07:40 - VLMP - DEBUG - [VLMP] Processing "system" component ({'type': 'simulationName', 'parameters': {'simulationName': 'Icosphere'}}), type "simulationName" (VLMP.py:194)
06/06/2025 16:07:40 - VLMP - WARNING - [VLMP] (system) Component name not specified, using "simulationName". 
06/06/2025 16:07:40 - VLMP - DEBUG - [VLMP] (system) Component name "simulationName". (VLMP.py:200)
06/06/2025 16:07:40 - VLMP

In [3]:

print("Number of particles:", icosphere.nparticles)
print("Radius od the icosphere:", icosphere.radius)

Number of particles: 362
Radius od the icosphere: 5.0


In [4]:
modes, eigenvalues = icosphere.obtain_modes()


Preliminary simulation structure created


[WARNING] UAMMD-structured Python wrapper is not compatible with UAMMD-structured self restarting mechanism


Read Hessian file /tmp/tmpcao2awfq/hessian.txt with shape (131044, 11)


[MESSAGE] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
[MESSAGE] ╻ ╻┏━┓┏┳┓┏┳┓╺┳┓
[MESSAGE] ┃ ┃┣━┫┃┃┃┃┃┃ ┃┃ Version: 2.5
[MESSAGE] ┗━┛╹ ╹╹ ╹╹ ╹╺┻┛
[MESSAGE] Compiled at: May 23 2025 13:23:39
[MESSAGE] Compiled in double precision mode
[MESSAGE] Computation started at Fri Jun  6 16:07:41 2025

[MESSAGE] [System] CUDA initialized
[MESSAGE] [System] Using device: NVIDIA GeForce RTX 3080 with id: 0
[MESSAGE] [System] Compute capability of the device: 8.6
[MESSAGE] ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ 
[MESSAGE] [ExtendedSystem] (system) Name: Icosphere
[MESSAGE] [ExtendedSystem] (system) Seed: 1749218861556563761
[MESSAGE] [GlobalDataBase] Fundamental not specified, using default fundamental, "Time"
[WARNING] [Time] No timeStep specified, using 0.0 as default.
[MESSAGE] [Basic] Loaded type A, mass: 1.000000, radius: 0.500000, charge: 0.000000
[MESSAGE] [ParticleData] Created with 362 particles.
[MESSAGE] [StateLoader] Loading property "id".
[MESSAGE] [S

In [31]:

precision = np.float32 if lm.SelfMobility.precision == "float" else np.float64
solver = lm.SelfMobility("open", "open", "open")
solver.setParameters(5)
solver.initialize(
    temperature=0.0,
    viscosity=1/(6 * np.pi ),
    hydrodynamicRadius=1.0,
    needsTorque=False,
)
positions = icosphere.positions.astype(precision)
assert positions.shape == (icosphere.nparticles, 3)
solver.setPositions(positions)
excited_mode = 0
force = - modes[:, excited_mode] * eigenvalues[excited_mode]
force = force.reshape((icosphere.nparticles, 3))
velocity = solver.Mdot(forces=force)[0]
projected_velocity = modes.T @ velocity.reshape((icosphere.nparticles * 3,))

print("Excited mode:", excited_mode)
print("Eigenvalue of the excited mode:", eigenvalues[excited_mode])

print("Velocity of the excited mode:", velocity)
print("Projected velocity shape:", projected_velocity.shape)
print("Projected velocity of the excited mode normalized:", projected_velocity / (-eigenvalues[excited_mode] ))

Excited mode: 0
Eigenvalue of the excited mode: -8.470487598460553e-15
Velocity of the excited mode: [[ 2.6428641e-28 -4.1864519e-16 -1.5147124e-16]
 [-2.5573974e-20 -4.1864519e-16 -1.5148119e-16]
 [ 1.0131878e-21 -4.1864993e-16 -1.5147241e-16]
 ...
 [-1.3531869e-20 -4.1861896e-16 -1.5146777e-16]
 [-1.5619619e-20 -4.1861536e-16 -1.5146737e-16]
 [-1.7785055e-20 -4.1861281e-16 -1.5146738e-16]]
Projected velocity shape: (1086,)
Projected velocity of the excited mode normalized: [ 1.00000000e+00  3.71168437e-10 -1.21091280e-14 ... -7.50493179e-10
  4.71457563e-14  1.69210718e-14]
